import { Vehicle, FinanceOption, User } from "@/types";

export const mockVehicles: Vehicle[] = [
    {
        id: "1",
        title: "2022 Honda City V CVT",
        type: "car",
        make: "Honda",
        model: "City",
        year: 2022,
        price: 1150000,
        mileage: 18000,
        fuelType: "petrol",
        transmission: "cvt",
        condition: "excellent",
        color: "Pearl White",
        owners: 1,
        location: "Hyderabad",
        description: "Single owner, company maintained with full service records. Top-end V CVT variant with sunroof, leather seats, and premium audio system.",
        features: ["Sunroof", "Leather Seats", "Push Start", "Cruise Control", "Alloy Wheels", "Android Auto & CarPlay"],
        images: [
            "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800",
            "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
            "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800",
        ],
        sellerId: "seller1",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
        views: 1250,
        saves: 89,
        isVerified: true,
        isFeatured: true,
        isActive: true,
    },
    {
        id: "2",
        title: "2021 Royal Enfield Classic 350",
        type: "bike",
        make: "Royal Enfield",
        model: "Classic 350",
        year: 2021,
        price: 175000,
        mileage: 12000,
        fuelType: "petrol",
        transmission: "manual",
        condition: "excellent",
        color: "Stealth Black",
        owners: 1,
        location: "Bangalore",
        description: "Well-maintained classic cruiser with all original parts. Perfect for long rides and city commute alike.",
        features: ["ABS", "Chrome Exhaust", "Luggage Carrier", "Engine Guard", "Phone Mount"],
        images: [
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
            "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800",
        ],
        sellerId: "seller2",
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-01-10"),
        views: 890,
        saves: 67,
        isVerified: true,
        isFeatured: true,
        isActive: true,
    },
    {
        id: "3",
        title: "2023 Maruti Swift ZXI+",
        type: "car",
        make: "Maruti Suzuki",
        model: "Swift",
        year: 2023,
        price: 875000,
        mileage: 8000,
        fuelType: "petrol",
        transmission: "manual",
        condition: "excellent",
        color: "Solid Fire Red",
        owners: 1,
        location: "Mumbai",
        description: "Latest model Swift with sporty looks. Top variant with all features. Extended warranty available.",
        features: ["LED Headlights", "SmartPlay Studio", "Auto Climate Control", "Rear Parking Sensors", "Keyless Entry"],
        images: [
            "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
            "https://images.unsplash.com/photo-1493238792000-8113da705763?w=800",
        ],
        sellerId: "seller3",
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2024-01-20"),
        views: 2100,
        saves: 156,
        isVerified: true,
        isFeatured: true,
        isActive: true,
    },
    {
        id: "4",
        title: "2020 Hyundai Creta SX(O)",
        type: "car",
        make: "Hyundai",
        model: "Creta",
        year: 2020,
        price: 1450000,
        mileage: 35000,
        fuelType: "diesel",
        transmission: "automatic",
        condition: "good",
        color: "Polar White",
        owners: 2,
        location: "Delhi",
        description: "Top-end Creta with all premium features. Diesel automatic for great mileage on highways.",
        features: ["Panoramic Sunroof", "Ventilated Seats", "360 Camera", "BOSE Audio", "Wireless Charging"],
        images: [
            "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800",
            "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800",
        ],
        sellerId: "seller4",
        createdAt: new Date("2024-01-08"),
        updatedAt: new Date("2024-01-08"),
        views: 1780,
        saves: 123,
        isVerified: true,
        isFeatured: false,
        isActive: true,
    },
    {
        id: "5",
        title: "2022 TVS Apache RTR 200",
        type: "bike",
        make: "TVS",
        model: "Apache RTR 200",
        year: 2022,
        price: 145000,
        mileage: 15000,
        fuelType: "petrol",
        transmission: "manual",
        condition: "excellent",
        color: "Matte Blue",
        owners: 1,
        location: "Chennai",
        description: "Performance-oriented sports bike in pristine condition. Race-inspired design with excellent handling.",
        features: ["Dual-Channel ABS", "Riding Modes", "SmartXConnect", "LED DRL", "Slipper Clutch"],
        images: [
            "https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800",
            "https://images.unsplash.com/photo-1547549082-6bc09f2049ae?w=800",
        ],
        sellerId: "seller5",
        createdAt: new Date("2024-01-12"),
        updatedAt: new Date("2024-01-12"),
        views: 650,
        saves: 45,
        isVerified: true,
        isFeatured: false,
        isActive: true,
    },
    {
        id: "6",
        title: "2019 Tata Nexon XZ+",
        type: "car",
        make: "Tata",
        model: "Nexon",
        year: 2019,
        price: 725000,
        mileage: 42000,
        fuelType: "petrol",
        transmission: "manual",
        condition: "good",
        color: "Calgary White",
        owners: 2,
        location: "Pune",
        description: "5-star safety rated compact SUV. Well maintained with regular servicing at authorized center.",
        features: ["Sunroof", "Harman Audio", "Rain Sensing Wipers", "Rear AC Vents", "Hill Assist"],
        images: [
            "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800",
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
        ],
        sellerId: "seller6",
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-01-05"),
        views: 920,
        saves: 78,
        isVerified: true,
        isFeatured: false,
        isActive: true,
    },
    {
        id: "7",
        title: "2023 Ola S1 Pro",
        type: "scooter",
        make: "Ola Electric",
        model: "S1 Pro",
        year: 2023,
        price: 135000,
        mileage: 5000,
        fuelType: "electric",
        transmission: "automatic",
        condition: "excellent",
        color: "Jet Black",
        owners: 1,
        location: "Hyderabad",
        description: "Premium electric scooter with 180km range. Fast charging capable with MoveOS 3 features.",
        features: ["181km Range", "Fast Charging", "Cruise Control", "Hypermode", "Music Speakers"],
        images: [
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
        ],
        sellerId: "seller7",
        createdAt: new Date("2024-01-18"),
        updatedAt: new Date("2024-01-18"),
        views: 1450,
        saves: 112,
        isVerified: true,
        isFeatured: true,
        isActive: true,
    },
    {
        id: "8",
        title: "2021 BMW 3 Series 320d",
        type: "car",
        make: "BMW",
        model: "3 Series",
        year: 2021,
        price: 3800000,
        mileage: 28000,
        fuelType: "diesel",
        transmission: "automatic",
        condition: "excellent",
        color: "Mineral Grey",
        owners: 1,
        location: "Mumbai",
        description: "Luxury sedan with M Sport package. Single owner with complete service history at BMW.",
        features: ["M Sport Package", "Harman Kardon Audio", "Gesture Control", "BMW Display Key", "Wireless CarPlay"],
        images: [
            "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
            "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800",
        ],
        sellerId: "seller8",
        createdAt: new Date("2024-01-22"),
        updatedAt: new Date("2024-01-22"),
        views: 3200,
        saves: 234,
        isVerified: true,
        isFeatured: true,
        isActive: true,
    },
];

export const mockFinanceOptions: FinanceOption[] = [
    {
        id: "1",
        lenderName: "HDFC Bank",
        logo: "https://logo.clearbit.com/hdfcbank.com",
        interestRate: 8.5,
        minTenure: 12,
        maxTenure: 84,
        minAmount: 100000,
        maxAmount: 10000000,
        processingFee: 0.5,
        features: ["Quick Approval", "No Hidden Charges", "Flexible EMI Options", "Pre-approved for existing customers"],
    },
    {
        id: "2",
        lenderName: "ICICI Bank",
        logo: "https://logo.clearbit.com/icicibank.com",
        interestRate: 8.75,
        minTenure: 12,
        maxTenure: 72,
        minAmount: 100000,
        maxAmount: 8000000,
        processingFee: 0.5,
        features: ["Instant Approval", "Zero Foreclosure Charges", "Digital Documentation", "Doorstep Service"],
    },
    {
        id: "3",
        lenderName: "SBI",
        logo: "https://logo.clearbit.com/sbi.co.in",
        interestRate: 8.25,
        minTenure: 12,
        maxTenure: 84,
        minAmount: 50000,
        maxAmount: 15000000,
        processingFee: 0.4,
        features: ["Lowest Interest Rate", "Maximum Tenure", "Minimum Documentation", "Pan-India Coverage"],
    },
    {
        id: "4",
        lenderName: "Axis Bank",
        logo: "https://logo.clearbit.com/axisbank.com",
        interestRate: 9.0,
        minTenure: 12,
        maxTenure: 60,
        minAmount: 100000,
        maxAmount: 5000000,
        processingFee: 0.5,
        features: ["Same Day Disbursement", "No Prepayment Penalty", "Online Application", "Flexible Repayment"],
    },
];

export const mockUsers: User[] = [
    {
        id: "seller1",
        name: "Rajesh Kumar",
        email: "rajesh@example.com",
        phone: "+91 98765 43210",
        avatar: "https://randomuser.me/api/portraits/men/32.jpg",
        role: "seller",
        isVerified: true,
        location: "Hyderabad",
        createdAt: new Date("2023-06-15"),
        savedVehicles: [],
    },
    {
        id: "seller2",
        name: "Priya Sharma",
        email: "priya@example.com",
        phone: "+91 98765 43211",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        role: "seller",
        isVerified: true,
        location: "Bangalore",
        createdAt: new Date("2023-08-20"),
        savedVehicles: [],
    },
];

export const vehicleMakes = {
    car: ["Maruti Suzuki", "Hyundai", "Tata", "Honda", "Toyota", "Mahindra", "Kia", "BMW", "Mercedes", "Audi"],
    bike: ["Royal Enfield", "Honda", "TVS", "Bajaj", "Yamaha", "KTM", "Harley-Davidson", "Suzuki"],
    scooter: ["Honda", "TVS", "Ola Electric", "Ather", "Suzuki", "Hero", "Vespa"],
};

export const locations = [
    "Hyderabad",
    "Bangalore",
    "Mumbai",
    "Delhi",
    "Chennai",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
];
